name: Schema

on:
  schedule:
    #    - cron: "0 0 */2 * *"
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

        # run program, return from it something somehow and check here if we need to commit and push

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: "manifest ${{ steps.manifestId.outputs.content }}"
